config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :users
  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_choice#, class_name: "UserChoice"
 has_and_belongs_to_many :rooms
end

app/models/user_choice.rb
class UserChoice < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end
  def show
    @room = Room.find(params[:id])
    @users = @room.users
if @room.winners
    w = @room.winners
    @winners = ""
    w.each do |x|
      winer = User.find_by(user_id: x)
      @winners += "#{winer.first_name} #{winer.last_name} #{winer.username}, "
    end
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adminka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <tr>
    <th>Stake</th>
    <th>Number of players</th>
    <th>Number of Winners</th>
    <th>Date</th>
    <th>Status</th>
    <th>First winner</th>
    <th>Second winner</th>
    <th>Third winner</th>
    <th></th>
  </tr>

  <% @rooms.each do |room| %>
    <tr>
      <td><%= room.stake %></td>
      <td><%= room.num_of_players %></td>
      <td><%= room.num_of_winners %></td>
      <td><%= room.updated_at %></td>
      <td><%= room.status %></td>
      <%    winners = [] %>
<% if room.winners %>
      <%    w = room.winners %>
      <% w.each do |x|%>
        <%  winner = User.find_by(user_id: x)%>
        <%  winners.push("#{winner.first_name} #{winner.last_name} #{winner.username}") %>
        <% end %>
<% end %>
      <td><%= winners[0] %></td>
      <td><%= winners[1] %></td>
      <td><%= winners[2] %></td>
      <td><%= link_to 'Show', room_path(room) %></td>
    </tr>
  <% end %>
</table>

app/views/rooms/show.html.erb
<p>
  <strong>Stake:</strong>
  <%= @room.stake %>
</p>
<p>
  <strong>Number of players:</strong>
  <%= @room.num_of_players %>
</p>

<p>
  <strong>Number of Winners:</strong>
  <%= @room.num_of_winners %>
</p>

<p>
  <strong>Date:</strong>
  <%= @room.updated_at %>
</p>

<p>
  <strong>Players in the room:</strong>
  <%= @users.size %>
</p>

<p>
  <strong>Winners:</strong>
  <%= @winners %>
</p>
<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>
  <strong> Players: </strong>
<% @users.each do |user| %>
    <%= user.user_id %>
    <%= user.first_name %>
    <%= user.last_name %>
    <%= user.username %>
<% end %>
</p>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>User ID</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Username</th>
    <th>In game?</th>
    <th>Updated at</th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.user_id %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.username %></td>
      <td><%= user.in_game %></td>
      <td><%= user.updated_at %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<p>
  <strong>User ID:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>
<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<p>
  <strong>In game?:</strong>
  <%= @user.in_game %>
</p>
<p>
  <strong>Updated at:</strong>
  <%= @user.updated_at %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<%= link_to 'Rooms', controller: 'rooms' %>
<%= link_to 'Users', controller: 'users' %>